Add RU
Flibio/EconomyLite pull request #42
Opened 2017-04-22 17:11 UTC by PixelmonPRO

Add Russian localization :)

2017-04-23 23:22 UTC, Flibio commented
Thanks, I'll take a look at this when I have time.

2017-05-09 22:06 UTC, Flibio commented
This is going to require some changing to the core of the message code in EconomyLite, so I'll save this for the next big update to EconomyLite.

2017-07-07 03:51 UTC, Flibio commented
I'm not sure if I want to include this in the main EconomyLite plugin. Everytime I modify a message in EconomyLite would require an update from you, severely slowing down the update process.

I believe the solution I am going to use is adding a list of translators on the EconomyLite Docs. I will include a link to your translated file, and the user has the option to download the file. I'll send you a link where you can contribute when I get it setup.

2018-02-11 11:46 UTC, Foxgreat commented
it's fine, we will control your mod and update hole lang files. It's on our interests)

2018-02-11 12:37 UTC, Foxgreat requested changes
please add this before merge

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.balanceother"="&6{player}'s Баланс: &a{balance} &6{label}"
command.balanceother="&6Баланс {player}: &a{balance} &6{label}"

This will be more correct, than how it is right now

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.baltop.invalidpage"="&cНедействительный номер страницы!"
command.baltop.invalidpage="&cНеправильный номер страницы!"

more simple, better to understand for player

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.changed"="&6Изменил валюту на &a{currency}!"
command.currency.changed="&6Валюта изменена на &a{currency}!"

more correct for this function

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +#
Aww, c'mon use outsource licence, this have no power on this document. Only oversizing document with this without any need

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.payed"="&6Заплачено &a{amount} &6{label} к вашему ссудному балансу!"
module.loan.payed="&6Оплачено &a{amount} &6{label} на ваш кредитный баланс!"

player don't get what is "ссудному" will be. Take by one format.

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.partial"="&cВам предлагается частичная ссуда!"
module.loan.partial="&cВам предложили частичный кредит!"

player don't get what is "ссуда" will be. Take by one format.

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.noloan"="&cУ вас нет предлагаемого кредита!"
module.loan.noloan="&cВам не поступало кредитных предложений!"

More correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.full"="&cВаш ссудный баланс заполнен, вы должны сначала погасить некоторые кредиты!"
module.loan.full="&cВаш кредитный лимит исчерпан. Сперва Вы должны оплатить часть имеющихся кредитов!"

player don't get what is "ссуда" will be. Take by one format. Also will be more correct to say like that.

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.balance"="&6Текущий баланс ссуды: &a{balance} &6{label}"
module.loan.balance="&6Текущий кредитный баланс: &a{balance} &6{label}"

player don't get what is "ссуда" will be. Take by one format.

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"module.loan.ask"="&6Вы хотели бы получить кредит на &a{amount} &6{label}? (Используйте &a/loan accept &6или &a/loan deny&6)"
module.loan.ask="&6Вы действительно хотите одобрить кредит на сумму &a{amount} &6{label}? (Введите &a/loan accept &6или &a/loan deny&6)"

Here about payment agreement with bankeer, more correct will be like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +#
Remove from all branches " at the start, It updates and not work now.

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.pay.success"="&6{target} &aбыло успешно выплачено &6{amountandlabel}&a!"
command.pay.success="&6{target} &aуспешно получил оплату в размере: &6{amountandlabel}&a!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.pay.notyou"="&cВы не можете заплатить сами!"
command.pay.notyou="&cВы не можете заплатить самому себе!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.pay.confirmno"="&c{player} не будут оплачены!"
command.pay.confirmno="&c{player} не получит оплату!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.pay.confirm"="&a{player} не онлайн! Вы все еще хотите отправить платеж?"
command.pay.confirm="&a{player} не в сети! Вы все равно хотите заплатить?"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.noperm"="&cУ вас нет разрешения на запуск этой команды!"
command.noperm="&cВам не разрешено использовать эту команду!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.migrate.nomode"="&cВыберите действительный способ импорта!"
command.migrate.nomode="&cПожалуйста, выберите правильный режим переноса!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.migrate.fail"="&cИмпорт не удался!"
command.migrate.fail="&cОшибка переноса!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.migrate.confirm"="&cИмпорт переопределит любые существующие балансы. &6Введите &a/migrate <способ> yes &6для подтверждения импорта!"
command.migrate.confirm="&cПеренос заменит все существующие балансы. &6Введите &a/migrate <mode> yes &6, чтобы подтвердить перенос!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.migrate.completed"="&aПеремещение завершено!"
command.migrate.completed="&aПеренос завершен!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.econ.setfail"="&cНе удалось установить баланс {name}!"
command.econ.setfail="&cНе удалось установить баланс для {name}!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.selectnew"="&6Напишите &a/currency set <валюта> &6 чтобы изменить валюту или нажмите, чтобы сделать новую валюту!"
command.currency.selectnew="&6Введите &a/currency set <currency> &6, чтобы изменить валюту, или нажмите на новую валюту!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.invalid"="&cЭта валюта не найдена!"
command.currency.invalid="&cТакая валюта не найдена!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.exists"="&cЭта валюта уже существует!"
command.currency.exists="&cТакая валюта уже существует!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.deleted"="&6Удалить валюту &a{currency}!"
command.currency.deleted="&6Удалена валюта &a{currency}!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.deleteconfirm"="&6Нажмите на это сообщение, чтобы подтвердить удаление &a{currency}!"
command.currency.deleteconfirm="&6Нажмите на это сообщение, чтобы подтвердить удаление валюты &a{currency}!"

more correct to say like that

2018-02-11 12:37 UTC, Foxgreat commented on src/main/resources/messages_RU.conf
> +"command.currency.confirm"="&6Нажмите на это сообщение, чтобы подтвердить &a{currency}!"
command.currency.confirm="&6Нажмите на сообщение для подтверждения перехода на валюту &a{currency}!"

more correct to say like that

2023-01-30 19:50 UTC, closed without merging